<script lang="ts">
    enum ALERTSOUNDS {
        DEFAULT = "Default",
        MAIL = "Mail",
        IM = "IM",
        REMINDER = "Reminder",
        SMS = "SMS",
        ALARM = "Alarm",
        ALARM2 = "Alarm2",
        ALARM3 = "Alarm3",
        ALARM4 = "Alarm4",
        ALARM5 = "Alarm5",
        ALARM6 = "Alarm6",
        ALARM7 = "Alarm7",
        ALARM8 = "Alarm8",
        ALARM9 = "Alarm9",
        ALARM10 = "Alarm10",
        CALL = "Call",
        CALL2 = "Call2",
        CALL3 = "Call3",
        CALL4 = "Call4",
        CALL5 = "Call5",
        CALL6 = "Call6",
        CALL7 = "Call7",
        CALL8 = "Call8",
        CALL9 = "Call9",
        CALL10 = "Call10",
    }
</script>
